language: go

addons:
  apt:
    packages:
      - python-psycopg2
      - python-nose
      - python-shapely
      - osmosis

before_script:
  - psql -U postgres -c "create extension postgis"

install:
  - go get github.com/tools/godep

script: make