dist: trusty
sudo: false

language: go

go:
  # - "1.8.x"
  # - "1.9.x"
  - stable


env:
  global:
    - GEOS_VERSION=3.6.2
    - PROTOBUF_VERSION=3.5.1
    # NOTE increase DEPS_REVISION everytime one of the compiled dependencies
    # changes!
    - DEPS_REVISION=1
    - PREFIX=${HOME}/local-${DEPS_REVISION}

    - CGO_CFLAGS=-I${PREFIX}/include
    - CGO_LDFLAGS=-L${PREFIX}/lib
    - LD_LIBRARY_PATH=${PREFIX}/lib
    - PKG_DIR=/tmp/imposm_packaging
    - PGUSER=postgres

    # enable ccache by updating PATH
    - PATH=/usr/lib/ccache:$PATH
    - CCACHE_TEMPDIR=/tmp/.ccache-temp

cache:
  directories:
    - ${HOME}/.ccache
    - ${PREFIX}

addons:
    postgresql: "9.5"
    apt:
      # List of whitelisted in travis packages for ubuntu-trusty can be found here:
      #   https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
      packages:
        - postgresql-9.5-postgis-2.3
        - osmosis
        - chrpath

before_script:
  - psql -U postgres -c 'create database travis' || true
  - psql -U postgres -c "create extension if not exists postgis"
  - psql -U postgres -c "create extension if not exists hstore"


before_install:
  - ccache --show-stats

  # build GEOS
  - |
    if [[ ! -e ${PREFIX}/lib/libgeos_c.so ]]; then
      curl -fsSL http://download.osgeo.org/geos/geos-${GEOS_VERSION}.tar.bz2 | tar -jxf - -C ${HOME}/build
      cd ${HOME}/build/geos-${GEOS_VERSION}
      ./configure --prefix=$PREFIX
      make -j2
      make install
    fi

  # build LevelDB
  - |
    if [[ ! -e ${PREFIX}/lib/liblevel* ]]; then
      mkdir -p ${HOME}/build/leveldb
      curl -fsSL https://github.com/google/leveldb/archive/master.tar.gz | tar -zxf - --strip-components 1 -C ${HOME}/build/leveldb
      mkdir -p ${HOME}/build/leveldb/build
      cd ${HOME}/build/leveldb/build
      cmake .. -DBUILD_SHARED_LIBS=1 && make -j 2
      mkdir -p ${PREFIX}/{lib,include}
      cp -R ${HOME}/build/leveldb/build/liblevel* ${PREFIX}/lib/
      cp -R ${HOME}/build/leveldb/include/leveldb ${PREFIX}/include/
    fi

  # build protobuf
  # - curl -fsSL https://github.com/google/protobuf/releases/download/v${PROTOBUF_VERSION}/protobuf-all-${PROTOBUF_VERSION}.tar.gz | tar -zxf - -C ${HOME}/build
  # - cd ${HOME}/build/protobuf-${PROTOBUF_VERSION}/ && ./configure --prefix=${PREFIX} && make -j2 && make install

  - ccache --show-stats

script:
  - cd ${TRAVIS_BUILD_DIR}
  - LEVELDB_POST_121=1 make

before_deploy:
  - mkdir -p ${PKG_DIR}/lib
  - cd ${TRAVIS_BUILD_DIR}
  - cp imposm3 ${PKG_DIR}
  - cp example-mapping.json ${PKG_DIR}/mapping.json

  - cd ${PREFIX}/lib
  - cp libgeos_c.so ${PKG_DIR}/lib
  - ln -s libgeos_c.so ${PKG_DIR}/lib/libgeos_c.so.1
  - cp libgeos.so ${PKG_DIR}/lib
  - ln -s libgeos.so ${PKG_DIR}/lib/libgeos-${GEOS_VERSION}.so
  - cp -R libleveldb.so* ${PKG_DIR}/lib

  - chrpath ${PKG_DIR}/lib/libgeos_c.so -r '${ORIGIN}'

  - find ${PKG_DIR}
  - BUILD_VERSION=`${PKG_DIR}/imposm3 version`-linux-x86-64
  - mv ${PKG_DIR} /tmp/imposm3-${BUILD_VERSION}
  - cd /tmp && tar zcvf imposm3-${BUILD_VERSION}.tar.gz imposm3-${BUILD_VERSION}

  - cd ${TRAVIS_BUILD_DIR}

deploy:
  provider: releases
  api_key:
    secure: fBhtCy6vdxxxuLYuJWXeTHJb3SAZCCbUJncIvR9ZOLCDWMJAPBnzPoqJFbByWzl6XghVRwhy9fe/82vzqByKiB/AQpqGqBxlwA9dSsqvSQcQxomAoHKKfZVdOuxM2bLDW3v5pJpmFtCMwhWjgwIOb9WxnBVeLxBbsq2Ox49tgHw=
  file: /tmp/imposm3-${BUILD_VERSION}.tar.gz
  skip_cleanup: true
  on:
    repo: omniscale/imposm3
    tags: true
    go: stable


